# details: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - make

formats: all

python:
  install:
    - requirements: .
    - method: pip
      path: .
      extra_requirements: []
  system_packages: false

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false


submodules:
  include: []
  exclude: all
  recursive: false
